app:
  contact-events-topic: contact-events
  eventstore.implementation: cassandra


spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    producer:
      client-id: wordcount-application
      bootstrap-servers:
        - localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    cassandra:
      keyspace-name: contacts
#      username: cassandra
#      password: cassandra
      schema-action: "CREATE_IF_NOT_EXISTS"